# Generated by Django 5.0.2 on 2024-02-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_telefono_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='telefono',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Seleccione el tipo de telefono', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telefonos', to='core.tipotelefono', verbose_name='Tipo de telefono'),
        ),
    ]
