# Generated by Django 5.0.2 on 2024-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipotelefono_telefono_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(help_text='Ingrese el número de telefono', max_length=255, verbose_name='Número de telefono'),
        ),
    ]
