# Generated by Django 5.0.2 on 2024-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=350, verbose_name='Alias')),
                ('codigo', models.CharField(max_length=350, verbose_name='codigo')),
                ('tipo', models.CharField(choices=[('Micro', 'Micro'), ('Chica', 'Chica'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=350, verbose_name='Tipo')),
                ('cod', models.CharField(blank=True, help_text='Codigo de campamento', max_length=50, null=True, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Campamento',
                'verbose_name_plural': 'Campamentos',
            },
        ),
    ]
