# Generated by Django 5.0.2 on 2024-02-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0008_historicalsucursal_es_central_sucursal_es_central_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsucursal',
            old_name='tipo',
            new_name='tamaño',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='tipo',
            new_name='tamaño',
        ),
    ]
