# Generated by Django 5.0.2 on 2024-02-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0009_rename_tipo_historicalsucursal_tamaño_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('permite_areas', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalsucursal',
            name='es_central',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='es_central',
        ),
        migrations.AddField(
            model_name='historicalsucursal',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='El tipo de sucursal.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sucursales.tiposucursal', verbose_name='Tipo de sucursal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='tipo',
            field=models.ForeignKey(help_text='El tipo de sucursal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='sucursales.tiposucursal', verbose_name='Tipo de sucursal'),
        ),
    ]
