# Generated by Django 5.0.2 on 2024-02-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_telefono_content_type'),
        ('sucursales', '0013_remove_area_estado_remove_historicalarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsucursal',
            name='localidad',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='La localidad de la sucursal.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.ForeignKey(help_text='La localidad de la sucursal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='core.localidad', verbose_name='Localidad'),
        ),
    ]
