# Generated by Django 5.0.2 on 2024-02-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sucursales', '0015_remove_empleado_sucursal_remove_puesto_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puesto',
            name='nivel_jerarquico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puesto',
            name='puesto_superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='sucursales.puesto'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='puestos', to='auth.permission'),
        ),
    ]
