# Generated by Django 5.0.2 on 2024-02-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0017_puesto_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='nivel_jerarquico',
        ),
    ]
