# Generated by Django 5.0.2 on 2024-02-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0018_remove_puesto_nivel_jerarquico'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='sucursales.area', verbose_name='Área'),
        ),
    ]
