# Generated by Django 5.0.2 on 2024-02-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0019_puesto_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='permisos',
        ),
    ]
