# Generated by Django 5.0.2 on 2024-02-15 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0021_area_gerente_area_historicalarea_gerente_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='gerente_area',
            field=models.ForeignKey(blank=True, help_text='El gerente de la área', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerente_area', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de área'),
        ),
        migrations.AlterField(
            model_name='area',
            name='jefe_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jefe_area', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de área'),
        ),
    ]
