# Generated by Django 5.0.2 on 2024-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0022_alter_area_gerente_area_alter_area_jefe_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalarea',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
