# Generated by Django 5.0.2 on 2024-02-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0024_historicaljerarquia_jerarquia_area_jerarquia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='jerarquia',
        ),
        migrations.RemoveField(
            model_name='historicalarea',
            name='jerarquia',
        ),
        migrations.AddField(
            model_name='puesto',
            name='jerarquia',
            field=models.ForeignKey(blank=True, help_text='La jerarquía de la área', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='sucursales.jerarquia', verbose_name='Jerarquía'),
        ),
    ]
