# Generated by Django 5.0.2 on 2024-02-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersonal',
            name='estudios',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='estudios',
        ),
        migrations.AddField(
            model_name='estudios',
            name='personal',
            field=models.ForeignKey(help_text='Seleccione el personal relacionado con este estudio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='personal.personal', verbose_name='Personal'),
        ),
        migrations.AddField(
            model_name='historicalestudios',
            name='personal',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione el personal relacionado con este estudio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personal.personal', verbose_name='Personal'),
        ),
    ]
