# Generated by Django 5.0.2 on 2024-02-14 15:34

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('sucursales', '0013_remove_area_estado_remove_historicalarea_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='ruc',
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='localidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='core.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección completa', max_length=350, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección completa', max_length=350, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='HistoricalProveedoresPorSucursal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cambiado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('sucursal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'historical proveedores por sucursal',
                'verbose_name_plural': 'historical proveedores por sucursals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRubroProveedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cambiado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rubro proveedor',
                'verbose_name_plural': 'historical rubro proveedors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTipoProveedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cambiado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tipo proveedor',
                'verbose_name_plural': 'historical tipo proveedors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProveedoresPorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_history', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_por_sucursal', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_por_sucursal', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sucursal',
            field=models.ManyToManyField(related_name='proveedores', through='proveedores.ProveedoresPorSucursal', to='sucursales.sucursal', verbose_name='Sucursales'),
        ),
        migrations.CreateModel(
            name='RubroProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_history', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='rubro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.rubroproveedor', verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.rubroproveedor', verbose_name='Rubro'),
        ),
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_history', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.tipoproveedor', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.tipoproveedor', verbose_name='Tipo'),
        ),
    ]
