# Generated by Django 5.0 on 2024-01-16 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
