# Generated by Django 5.0 on 2024-01-18 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernote',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='production_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_manager', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de producción'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_manager', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de pedido'),
        ),
    ]
